name: spherus-client-CI

on:
  push:
    tags:
      - "v*"

jobs:      
  dockerProd:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.12.2'

      - name: Install dependencies
        run: npm ci

      - name: Build the Vite project
        run: |
          VITE_URL_SPHERUS_API=https://staging.spherus.luc-dev.com/api npm run build

      - name: Copy dist build files to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "dist/*"
          target: /home/lukasz/apps/spherus/spherus-staging/client/${{ github.ref_name }}/
          strip_components: 1

      - name: Update NGINX volume inside docker-compose.stagig.yml 
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            VERSION=${{ github.ref_name }}
            STAGING_PATH="/home/lukasz/apps/spherus/spherus-staging"
            CLIENT_PATH="$STAGING_PATH/client"
            DEPLOY_PATH="$CLIENT_PATH/$VERSION"

            # Update docker-compose.spherus_staging.yml to point to the new volume for nginx
            sed -i "s|$CLIENT_PATH/v[^/]*|$DEPLOY_PATH:|" $STAGING_PATH/docker-compose.spherus_staging.yml || { echo "Failed to change docker-compose.spherus_staging.yml"; exit 1; }
            
            # Restart NGINX to apply the new configuration
            cd $STAGING_PATH
            docker compose -f docker-compose.spherus_staging.yml down &&
            docker compose -f docker-compose.spherus_staging.yml up -d

            echo "Deployment completed."